; PlatformIO Project Configuration File
; Smart Energy Monitor v3.0

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

; ① LittleFS partition — gunakan partisi default dengan LittleFS
board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    https://github.com/mandulaj/PZEM-004T-v30.git
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32
    tzapu/WiFiManager
    bblanchon/ArduinoJson @ ^6.21.5

; Upload filesystem image (jalankan: pio run --target uploadfs)
; Sebelum upload firmware pertama kali, jalankan ini untuk format LittleFS